[theme]
# Base theme (light)
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Dark theme overrides (will be applied via CSS)
[theme.dark]
primaryColor = "#1E88E5"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"

[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = true

[browser]
serverAddress = "localhost"

[runner]
fastRerun = true

[client]
showErrorDetails = true

[mapbox]
token = ""

[deprecation]
showfileUploaderEncoding = false

[logger]
level = "info"

[scheduler]
minValue = 0
maxValue = 100
value = 0

[viewer]
port = 3000

[viewer.theme]
base = "dark"
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
